server:
  port: 8090
spring:
  application:
    name: add-log

    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB

  messages:
    #i18n
    basename: messages/messages

############# DATA SOURCE ####################
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: H2Dialect
        format_sql: true

logging:
  level:
    org:
      hibernate:
        sql: info
